name: Run Tests

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

  workflow_dispatch:

jobs:
  stylechecker:
    runs-on: ubuntu-latest
    container: citus/stylechecker:latest
    steps:
    - uses: actions/checkout@v2
    - name: Run stylechecker
      run: citus_indent --check
